/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CompOption } from "./components/demo-component/demo.component";
export namespace Components {
    interface GsDemo {
        /**
          * If true, the button is displayed as disabled
         */
        "disabled": boolean;
        /**
          * This text which is shown as label
         */
        "label": string;
        /**
          * Is needed to reference the form data after the form is submitted
         */
        "name": string;
        /**
          * Define the available options in the drop-down list
         */
        "options": CompOption[];
    }
}
declare global {
    interface HTMLGsDemoElement extends Components.GsDemo, HTMLStencilElement {
    }
    var HTMLGsDemoElement: {
        prototype: HTMLGsDemoElement;
        new (): HTMLGsDemoElement;
    };
    interface HTMLElementTagNameMap {
        "gs-demo": HTMLGsDemoElement;
    }
}
declare namespace LocalJSX {
    interface GsDemo {
        /**
          * If true, the button is displayed as disabled
         */
        "disabled"?: boolean;
        /**
          * This text which is shown as label
         */
        "label"?: string;
        /**
          * Is needed to reference the form data after the form is submitted
         */
        "name"?: string;
        /**
          * Define the available options in the drop-down list
         */
        "options"?: CompOption[];
    }
    interface IntrinsicElements {
        "gs-demo": GsDemo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gs-demo": LocalJSX.GsDemo & JSXBase.HTMLAttributes<HTMLGsDemoElement>;
        }
    }
}
