/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GsDemo {
        /**
          * Name property to provide name as title
         */
        "name": string;
    }
}
declare global {
    interface HTMLGsDemoElement extends Components.GsDemo, HTMLStencilElement {
    }
    var HTMLGsDemoElement: {
        prototype: HTMLGsDemoElement;
        new (): HTMLGsDemoElement;
    };
    interface HTMLElementTagNameMap {
        "gs-demo": HTMLGsDemoElement;
    }
}
declare namespace LocalJSX {
    interface GsDemo {
        /**
          * Name property to provide name as title
         */
        "name"?: string;
    }
    interface IntrinsicElements {
        "gs-demo": GsDemo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gs-demo": LocalJSX.GsDemo & JSXBase.HTMLAttributes<HTMLGsDemoElement>;
        }
    }
}
